### PR TITLE
added Centrifuge and SHOGUN test databases

### PR DESCRIPTION
**Pull request by qiyunzhu**
Except for SHOGUN's functional profiling database, which I still have no idea how to make. @tanaes @mortonjt

### CODE REVIEW

**Comment by qiyunzhu** [comment]
@tanaes There are bzipped files under centrifuge, shogun/bt2, shogun/burst and shogun/utree. They need to be unzipped before using. I guess you have the trick to take care of unzipping. So I didn't do it.

**Comment by tanaes** [comment]
Ok great thank you!

**Comment by tanaes** [comment]
Cool this looks great, @qiyunzhu. Did you have a chance to actually execute the tools against these to test?

**Review by tanaes — APPROVED** [review]

**Comment by qiyunzhu** [comment]
@tanaes Yes I did. They all worked. You won't expect any meaningful profile being produced though, since the database is but phiX phage.

**Pull request merged**
