### PR TITLE
Shogun version update

### PR DESCRIPTION
**Pull request by tanaes**
This updates the shogun version to:
- be explicit (1.0.5), so should be robust to further github/conda versioning
- take advantage of the new pathway summarization functionality
- add pathway compatibility to test db

@qiyunzhu this modifies your original code, would you mind sanity checking (and maybe installing + testing on your own barnacle install?)

### CODE REVIEW

**Comment by qiyunzhu** [comment]
@tanaes Sorry for the late reply. This looks quite sane to me. It is good to know that they now have five catagories: 'kegg', 'modules', 'modcov', 'pathways', 'pathcov'. But they didn't do 'kegcov'. Therefore, I guess 'kegg' means relative abundance, does it?

**Comment by tanaes** [comment]
'kegg' is the per-gene annotation, so the 'coverage' concept doesn't apply.

**Comment by tanaes** [comment]
@qiyunzhu ok to merge?

**Comment by qiyunzhu** [comment]
@tanaes Got it! Merged.

**Pull request merged**
