### PR TITLE
merged raw rules into qc module

### PR DESCRIPTION
**Pull request by tanaes**
Addresses issue #56. 

@RNAer @mortonjt I didn't actually rename any of the `raw` rules, since the conceptual distinction still makes sense to me... what do you think?

### CODE REVIEW

**Comment by RNAer** [comment]
i think it is good

**Comment by tanaes** [comment]
@mortonjt can you merge?

**Comment by tanaes** [comment]
@qiyunzhu or @sjanssen2 would you mind checking/merging this small PR? Thanks!

**Comment by qiyunzhu** [comment]
@tanaes Sure! Let me read.

**Pull request merged**
