### PR TITLE
Improve launch script

### PR DESCRIPTION
**Pull request by tanaes**
Expands desired functionality from @mortonjt's PR #109, but don't merge yet! Just want to get going for comments. 

The install / uninstall both seem to be working! See Travis for an example. 

Surely some improvements to code can be done, so would be interested in input---for example, I think it might be possible to have a `--verbose` flag that echoed the Conda install output if desired. But the base functionality seems to be there.

For the DB installs, @qiyunzhu, I'm thinking that the best way to accomplish this is to actually include each of the included test_db folders as a separate tar.*z archive, and have an install_dbs.sh script with the unzip commands for each one. Make sense? If so, all of the .bz2'd files you have need to be unzipped in the usable version, right?

### CODE REVIEW

**Comment by qiyunzhu** [comment]
Hi @tanaes I totally agree with your idea of zipping each whole database into an archive.

**Review by qiyunzhu — APPROVED** [review]
Looks all good to me!

**Review by mortonjt — APPROVED** [review]
This looks awesome!  Thanks for putting this together!

**Comment by tanaes** [comment]
cool @mortonjt or @qiyunzhu want to merge? I've got a follow-on upcoming with some additional small fixes.

**Pull request merged**
