### PR TITLE
conda install file for module 'raw'

### PR DESCRIPTION
**Pull request by sjanssen2**

### CODE REVIEW

**Review by mortonjt — APPROVED** [review]

**Comment by mortonjt** [comment]
@tanaes what do you think?

**Comment by sjanssen2** [comment]
hey @tanaes can you please double check if I adhering to the latest file naming conventions?!

**Comment by tanaes** [comment]
Totally adhering to conventions as far as I can tell. 

Should this be merged with QC?

**Comment by sjanssen2** [comment]
I'd merge now as is and open an issue to merge with QC

**Review by tanaes — APPROVED** [review]

**Pull request merged**
