### PR TITLE
renamed mash as distance

### PR DESCRIPTION
**Pull request by qiyunzhu**
Renamed subdirectory "mash" as "distance".
Also commented out MetaPhlAn installation script to save some test time.

### CODE REVIEW

**Comment by tanaes** [comment]
I'm not sure I get why it is necessary to rename mash as distance?

**Comment by qiyunzhu** [comment]
@tanaes This is what we discussed earlier today. https://github.com/biocore/oecophylla/issues/27

**Comment by qiyunzhu** [comment]
I think there are multiple metrics and tools to calculate the distance between genomes: Mash, SourMash, pyani (ANI), compareM (AAI), our homebrew phyletic algorithm, Dan's novel k-mer algorithm, etc.

**Comment by qiyunzhu** [comment]
@RNAer @tanaes @mortonjt

**Comment by tanaes** [comment]
Ok that makes more sense to me 👍

**Comment by qiyunzhu** [comment]
@tanaes Great! Wanna merge?

**Pull request merged**
